openapi: 3.0.0
info:
  title: Password validator module
  version: v1
servers:
  - url: http://localhost:8081
paths:
  /password/validate:
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/validation_result"
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                type: string
                example: Bad request
        '422':
          $ref: "#/components/responses/trait_validate_422"
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Internal server error
      description: Validate password
      operationId: validatePassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/password"
        required: true
components:
  schemas:
    validation_result:
      $ref: schemas/validation_template.json
    password:
      $ref: schemas/password.json
    errors:
      $ref: schemas/errors.json
  responses:
    trait_validate_422:
      description: Validation errors
      content:
        application/json:
          example: examples/errors.sample
          schema:
            $ref: "#/components/schemas/errors"
