#%RAML 0.8

title: Password validator module
baseUri: http://api.example.com/{version}
version: v1

documentation:
  - title: mod-password-validator API
    content: This module is performing validation of the password and storing rules for the specified tenant.

schemas:
  - validation_template.json: !include validation_template.json
  - ruleCollection: !include ruleCollection.json
  - rule.json: !include rule.json

traits:
  - queryable:
      queryParameters:
        type:
          description: "A type of the validator."
          required: true
          type: string

/password:
  /validate:
    post:
      description: Validate password
      responses:
        200:
          body:
            application/json:
              schema: validation_template.json
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
  /validators:
    displayName: Rules
    description: Rules collection
    get:
      is: [queryable]
      responses:
        200:
          body:
            application/json:
              schema: ruleCollection
        404:
          description: "Rules not found"
          body:
            text/plain:
              example: "Rules not found"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
